version: "3.1"

services:

    wordpress:
        image: wordpress:latest
        ports:
            - "80:80"
        restart: always
        env_file: ./docker/.env
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        volumes:
            - ./wp-content/themes:/var/www/html/wp-content/themes
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
            - ./docker/php.ini:/usr/local/etc/php/php.ini

    db:
        image: mysql:5.7
        restart: always
        env_file: ./docker/.env
        volumes:
            - ./docker/db:/var/lib/mysql
            - ./docker/sql:/docker-entrypoint-initdb.d/install_wordpress.sql

volumes:
    db:
